spring:
  data:
    mongodb:
      authentication-database: admin
      username: lamph11
      password: open
      database: blog
      port: 27017
      host: 35.247.133.74

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
